### ISSUE TITLE
training

### ISSUE THREAD

**Issue by 943274923** [hchung12/espnet-asr#1]
how to training

**Comment by hchung12** [comment]
If you want to train model, you need to install full package of ESPnet following the [installation instruction](https://espnet.github.io/espnet/installation.html)

And then, if you want to reproduce the zeroth_korean model, run the run.sh in "egs2/zeroth_korean/asr1" directory in your local ESPnet.  Other models can be trained using the recipes in [recipes](https://github.com/hchung12/espnet-asr/tree/master/recipes).
