### ISSUE TITLE
평가 알고리즘 관련 질문

### ISSUE THREAD

**Issue by JoungheeKim** [hchung12/espnet-asr#2]
안녕하세요? 
좋은 알고리즘과 pre-trained 모델을 제공해 주셔서 감사합니다.

현재 코드와 약간은 무관한 질문이지만 해당 코드가 ETRI에서 2020년에 만든 논문인
KsponSpeech: Korean Spontaneous Speech Corpus for Automatic Speech Recognition, 2020
가 반영되어 있는 거 같아 논문과 관련된 질문을 몇개 드리고자 Issue를 남기게 되었습니다.

해당 논문에서 normalized Word Error Score(sWER)에 대한 언급이 있는데 관련코드를 찾기가 어렵습니다.
혹시 어디에 있는지 알 수 있을까요??
논문을 보고 sWER을 재현하는데 어려움이 있습니다.

Python 코드가 있다면 해당 코드를 남겨주시면 더 도움이 될 꺼 같습니다.
감사합니다.

**Comment by hchung12** [comment]
안녕하세요,

요청하신 내용은  @jubang0219 가 작성하신 ESPnet1 기반의 공식 recipe를 참고하시는 것이 좋을것 같습니다.
(이 저장소에서는 공식 recipe중 일부만을 참고해 ESPnet2용으로 작성된 recipe를 제공합니다)

ESPnet1 공식 recipe (https://github.com/espnet/espnet/blob/master/egs/ksponspeech/asr1/run.sh) 의
287~288라인 local/score_sclite.sh --bpe ${nbpe} --bpemodel ${bpemodel}.model   --wer true --space-norm true ${expdir}/${decode_dir} ${dict}와 같이 local/score_sclite.sh을 사용하면 space-norm 결과를 얻게 됩니다.

감사합니다.
