### ISSUE TITLE
kspon 데이터로 트레이닝방법

### ISSUE THREAD

**Issue by miziworld** [hchung12/espnet-asr#3]
espnet 사용한 프리트레이닝 모델 제공해주셔서 감사합니다.
우선은 재트레이닝을 시키려고하는데 espnet을 처음사용해보는것이라 몇가지 질문드립니다.

1. Kspon 데이터같은경우는 AI hub에서 다운받으면 KsponSpeech01-05.zip 의 5개 트레이닝 파일과 transcript 파일, eval파일이 포함되는데 경로설정을 어떻게 해주어야할까요?  
local_data_opt 경로설정과 train, dev, test_set 파일경로 지정과 trainscription 파일을 어떻게 해야할지 질문드립니다.

2. run.sh을 실행시키면 내부에서 asr.sh이 실행되고 그 안에서 다시 asr_train.py가호출되어사용되는것이맞을까요?
혹시거기서  quantization 옵션을사용할 수 있을까요?

3. 트레이닝된 weight값들은 어디에 저장되는지 알고싶습니다.

**Comment by hchung12** [comment]
공식 espnet 저장소의 recipe (https://github.com/espnet/espnet/tree/master/egs2/ksponspeech/asr1)를 참고하시는 것이 도움이 될것 같습니다.

1. AI Hub에서 Kspon데이타를 다운 받은 후 https://github.com/espnet/espnet/blob/master/egs2/ksponspeech/asr1/local/data.sh의 datadir를 다운 받은 Kspon 디렉토리로 설정하면 됩니다. 
2. 맞습니다. 그리고, model parameter quantization 옵션은 없는 것으로 알고 있습니다.
3. 훈련이 완료되면 asr1/exp/환경파일명/valid.acc.ave.pth  파일명으로 모델이 저장됩니다.

**Comment by miziworld** [comment]
빠른답변 감사드립니다..!!
개발자님이 제공해주신 pre-trained model 파라미터들을 확인해보고 싶은데 혹시 모델클래스가 어디에 정의되어있는지 확인할 수 있을까요..?

**Comment by hchung12** [comment]
bin/asr_inference.py 코드에서 asr_model을 사용하시면 됩니다. asr_model에 대한 다음과 같이 파라메타를 출력하면 확인 가능합니다.

for name, param in asr_model.named_parameters():
  if param.requires_grad:
  print(name, param.data)

**Comment by miziworld** [comment]
감사합니다!

1. 혹시 개발자님께서는 KsponSpeech 데이터에 관한 모델같은 경우 original espnet 튜토리얼을 따라 다르게 바꾼점 없이 그대로training시키신걸까요?  
2. fast decoder의 차이와 기본 디코더의 차이가 어떤것일지 궁금합니다.
3. 제공해주신  pretrained model을 압축해제하였을때 나오는 data, exp, meta.yaml은 기본 recipe대로 진행하였을때 생성되는 파일들인가요?

**Comment by hchung12** [comment]
1. original 튜토리얼과는 다르면 이는 제가 배포한 recipe (https://github.com/hchung12/espnet-asr/tree/master/recipes)를 original과 비교해 보시면 그 차이를 알수 있으실 겁니다.
2. 종단형 음성인식기에서 입력 신호의 길이에 대해 EOS 출력 이 언제쯤 끝날지를 대기 시간의 차이와 얼마나 많은 부분 정답을 유지할지 차이로 보시면 될것 같습니다. fast decoding에서는 입력 신호 (encoding 벡터 열) * 0.3 정도를 기다리며 부분 정답도 적게 유지합니다.
3. official recipe가 아닌 제 recipe(https://github.com/hchung12/espnet-asr/tree/master/recipes)를 사용했을때 출력된 결과입니다.

**Comment by miziworld** [comment]
감사합니다.!!
오리지널 사이트의 디코딩 부분보다 수정해서 공개해주신 인퍼런스 파트가 사용이 편리해서 잘 사용하고 있습니다.
혹시 제공해주신 recipe는 espnet2에 관련해서만 사용가능한 것으로 알고있는데 espnet1에서 사용가능하도록 개발해주신  inference 코드도 있을까요?

**Comment by hchung12** [comment]
espnet1용으로는 inference 코드와 모델 훈련 작업을 수행하지 않았습니다.

**Comment by miziworld** [comment]
안녕하세요 제공해주신 코드를 아주 유용하게 사용하고 있습니다. 
그러던 중 몇가지 궁금증이 생겨 다시 질문드리게 되었습니다.
 
1. 똑같은 test set으로 원래 original espnet에서 디코딩 스테이지를 사용하는 것보다 제공해주신 코드를 사용하는것이 디코딩 속도가 더 빠르게 느껴지는데 이는 데이터 로드를 한꺼번에 한다음에 디코딩 처리만 순차적으로 해주어서 그런것일까요?  원래 recipe에서 어떤 부분을 수정하신것인지 알 수 있을까요?
2.  bin/asr_inference.py에서 asr_model에 모델이 저장되는것 같은데 torchsummary를 이용해서 레이어별 파라미터를 확인하고자 할 때 input shape를 몇으로 넣어주는게 맞나요?
ex) summary(your_model, input_size=(channels, H, W))
3. espnet1에서 훈련된 pth 모델을 제공해주신 코드에서 이용하는것은 아예 불가능할까요..?
